name: Construir APK GATO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar SDK Android 36
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Descomprimir proyecto
        run: |
          mkdir gato_project
          unzip -q GATO_ANDROID_API36_GITHUB.zip -d gato_project

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name:
